services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: localnet-ipfs
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
    networks:
      sonrnet:
        ipv4_address: 172.16.238.2

  sonr0:
    container_name: localnet-sonr-node0
    build:
      context: $SONR_CODE_DIR
      dockerfile: docker/Dockerfile.localnet
    environment:
      - IPFS_ADDRESS=localnet-ipfs:4001
      - IPFS_API_ADDRESS=localnet-ipfs:5001
      - VAULT_API_ADDRESS=localnet-sonr-vault:8888
    ports:
      - 1317:1317
      - 2345:2345
      - 26656-26657:26656-26657
      - 9090:9090
      - 4500:4500
    networks:
      sonrnet:
        ipv4_address: 172.16.238.3
    depends_on:
      - ipfs

  sonr-vault:
    container_name: localnet-sonr-vault
    build:
      context: $SONR_VAULT_CODE_DIR
      dockerfile: docker/Dockerfile.localnet
    volumes:
      - ipfs_path:/home/sonr-vault-user/.ipfs
    environment:
      - PORT=8888
      - IPFS_API_ADDR=172.16.238.2:5001
        #- IPFS_PATH="~/.ipfs"
      - SONR_RPC_ADDR_PUBLIC=172.16.238.3:9090
    command: "--skip-chain-validation"
    ports:
      - 127.0.0.1:8888:8888
    networks:
      sonrnet:
        ipv4_address: 172.16.238.4
    depends_on:
      - sonr0

volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:
  sonr_genesis:

networks:
  sonrnet:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

